# Generated by Django 3.0.3 on 2020-07-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.ImageField(blank=True, default='static/images/blog-2.jpg', upload_to='images/certificate/'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
