# Generated by Django 3.0.3 on 2020-07-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200712_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='images/blog/blog-2.jpg', upload_to='images/blog/'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.ImageField(blank=True, default='images/certificate/blog-2.jpg', upload_to='images/certificate/'),
        ),
    ]
